from decimal import Decimal

MAX_REGEX_LENGTH = 250
CASE_INSENSITIVE_MATCHING = True
DEFAULT_MATCH_MODE = "balanced"
MIN_SINGLE_WORD_SUFFIX_LENGTH = 8
MIN_MULTI_WORD_SUFFIX_LENGTH = 6

DEFAULT_QUANTITY = 1
DEFAULT_TOTAL = Decimal("0")

CSV_ENCODING = "utf-8-sig"
DEFAULT_STORAGE_FILENAME = "saved_regex.json"
